In [2]:
import numpy as np
import pandas as pd

In [68]:
metadata = pd.read_csv("Hoplo_meta_data_2.csv", index_col="Seq ID")
#metadata = metadata.drop(["HOOC0024", "HOOC0039", "HOOC0047"])
#metadata.index = [x+".trimmed" for x in metadata.index]
metadata

         Sample ID Location  Vegetation zone longitude
Seq ID
HOOC0001     HBG 1  Badagry  Mangrove Forest      BAIK
HOOC0002     HBG 2  Badagry  Mangrove Forest      BAIK
HOOC0003      HBG3  Badagry  Mangrove Forest      BAIK
HOOC0004      HBG4  Badagry  Mangrove Forest      BAIK
HOOC0005      HBG5  Badagry  Mangrove Forest      BAIK
...            ...      ...              ...       ...
HOOC0092     HIG6    Igbeti   Giunea savanna     EIBSI
HOOC0093      HIG7   Igbeti   Giunea savanna     EIBSI
HOOC0094      HIG8   Igbeti   Giunea savanna     EIBSI
HOOC0095     HIG9    Igbeti   Giunea savanna     EIBSI
HOOC0096    HIG10    Igbeti   Giunea savanna     EIBSI

[96 rows x 4 columns]

In [69]:
correct_orientation = pd.DataFrame(metadata["Sample ID"].values.reshape(8,12))
correct_orientation

,0,1,2,3,4,5,6,7,8,9,10,11
0,HBG 1,HBG 2,HBG3,HBG4,HBG5,HBG6,HBG7,HBG8,HBG9,HBG10,HIK1,HIK2
1,HIK3,HIK5,HIK6,HIK7,HIK8,HIK9,HlK10,HEP1,HEP2,HEP3,HEP4,HEP5
2,HEP6,HEP7,HEP8,HEP9,HEP10,HIB 1,HIB 2,HIB 3,HIB 4,HIB 5,HIB 6,HIB 7
3,HIB 9,HIB 10,HAB1,HAB2,HAB3,HAB4,HAB5,HAB6,HAB7,HAB8,HAB9,HAB10
4,H IF 1,H IF 2,H IF 3,H IF 4,H IF 5,H IF 6,H IF 7,H IF 8,H IF 9,H IF 10,HIW1,HIW2
5,HIW3,HIW4,HIW5,HIW6,HIW7,HIW8,HIW9,HIW10,H AD 1,H AD 2,H AD 3,H AD 4
6,H AD 5,H AD 6,H AD 7,H AD 8,HSK1,HSK2,HSK3,HSK4,HSK5,HSK6,HSK7,HSK8
7,HSK9,HSK10,HIG1,HIG2,HIG3,HIG4,HIG5,HIG6,HIG7,HIG8,HIG9,HIG10

# Read across rows write down columns

In [70]:
tsids = pd.DataFrame(correct_orientation.values.ravel().reshape(12,8)).T
tsids

,0,1,2,3,4,5,6,7,8,9,10,11
0,HBG 1,HBG9,HIK8,HEP6,HIB 4,HAB3,H IF 1,H IF 9,HIW7,H AD 5,HSK5,HIG3
1,HBG 2,HBG10,HIK9,HEP7,HIB 5,HAB4,H IF 2,H IF 10,HIW8,H AD 6,HSK6,HIG4
2,HBG3,HIK1,HlK10,HEP8,HIB 6,HAB5,H IF 3,HIW1,HIW9,H AD 7,HSK7,HIG5
3,HBG4,HIK2,HEP1,HEP9,HIB 7,HAB6,H IF 4,HIW2,HIW10,H AD 8,HSK8,HIG6
4,HBG5,HIK3,HEP2,HEP10,HIB 9,HAB7,H IF 5,HIW3,H AD 1,HSK1,HSK9,HIG7
5,HBG6,HIK5,HEP3,HIB 1,HIB 10,HAB8,H IF 6,HIW4,H AD 2,HSK2,HSK10,HIG8
6,HBG7,HIK6,HEP4,HIB 2,HAB1,HAB9,H IF 7,HIW5,H AD 3,HSK3,HIG1,HIG9
7,HBG8,HIK7,HEP5,HIB 3,HAB2,HAB10,H IF 8,HIW6,H AD 4,HSK4,HIG2,HIG10

In [71]:
metadata["tsids"] = tsids.values.ravel()
metadata

         Sample ID Location  Vegetation zone longitude   tsids
Seq ID
HOOC0001     HBG 1  Badagry  Mangrove Forest      BAIK   HBG 1
HOOC0002     HBG 2  Badagry  Mangrove Forest      BAIK    HBG9
HOOC0003      HBG3  Badagry  Mangrove Forest      BAIK    HIK8
HOOC0004      HBG4  Badagry  Mangrove Forest      BAIK    HEP6
HOOC0005      HBG5  Badagry  Mangrove Forest      BAIK   HIB 4
...            ...      ...              ...       ...     ...
HOOC0092     HIG6    Igbeti   Giunea savanna     EIBSI    HIW6
HOOC0093      HIG7   Igbeti   Giunea savanna     EIBSI  H AD 4
HOOC0094      HIG8   Igbeti   Giunea savanna     EIBSI    HSK4
HOOC0095     HIG9    Igbeti   Giunea savanna     EIBSI    HIG2
HOOC0096    HIG10    Igbeti   Giunea savanna     EIBSI  HIG10

[96 rows x 5 columns]

In [92]:
metadata[metadata["Sample ID"] == "HBG 1"][["Vegetation zone", "longitude", "Location"]]
metadata[metadata["tsids"] == "HBG 1"]
metadata.tsids

tmp = metadata.copy()
tmp.index = tmp["Sample ID"]
tdf = tmp.loc[metadata.tsids][["Vegetation zone", "longitude", "Location"]]
#pd.concat([metadata, tdf], axis=1)
tdf.index = metadata.index
tdf["Sample ID"] = metadata.tsids
tdf.to_csv("Hoplo_metadata_transpose_V1.csv")

# Reading columns and writing rows
## This is the one that works

In [104]:
tsids = pd.DataFrame(correct_orientation.T.values.reshape(8, 12))
tsids

,0,1,2,3,4,5,6,7,8,9,10,11
0,HBG 1,HIK3,HEP6,HIB 9,H IF 1,HIW3,H AD 5,HSK9,HBG 2,HIK5,HEP7,HIB 10
1,H IF 2,HIW4,H AD 6,HSK10,HBG3,HIK6,HEP8,HAB1,H IF 3,HIW5,H AD 7,HIG1
2,HBG4,HIK7,HEP9,HAB2,H IF 4,HIW6,H AD 8,HIG2,HBG5,HIK8,HEP10,HAB3
3,H IF 5,HIW7,HSK1,HIG3,HBG6,HIK9,HIB 1,HAB4,H IF 6,HIW8,HSK2,HIG4
4,HBG7,HlK10,HIB 2,HAB5,H IF 7,HIW9,HSK3,HIG5,HBG8,HEP1,HIB 3,HAB6
5,H IF 8,HIW10,HSK4,HIG6,HBG9,HEP2,HIB 4,HAB7,H IF 9,H AD 1,HSK5,HIG7
6,HBG10,HEP3,HIB 5,HAB8,H IF 10,H AD 2,HSK6,HIG8,HIK1,HEP4,HIB 6,HAB9
7,HIW1,H AD 3,HSK7,HIG9,HIK2,HEP5,HIB 7,HAB10,HIW2,H AD 4,HSK8,HIG10

In [105]:
metadata["tsids"] = tsids.values.ravel()
metadata

         Sample ID Location  Vegetation zone longitude   tsids
Seq ID
HOOC0001     HBG 1  Badagry  Mangrove Forest      BAIK   HBG 1
HOOC0002     HBG 2  Badagry  Mangrove Forest      BAIK    HIK3
HOOC0003      HBG3  Badagry  Mangrove Forest      BAIK    HEP6
HOOC0004      HBG4  Badagry  Mangrove Forest      BAIK   HIB 9
HOOC0005      HBG5  Badagry  Mangrove Forest      BAIK  H IF 1
...            ...      ...              ...       ...     ...
HOOC0092     HIG6    Igbeti   Giunea savanna     EIBSI   HAB10
HOOC0093      HIG7   Igbeti   Giunea savanna     EIBSI    HIW2
HOOC0094      HIG8   Igbeti   Giunea savanna     EIBSI  H AD 4
HOOC0095     HIG9    Igbeti   Giunea savanna     EIBSI    HSK8
HOOC0096    HIG10    Igbeti   Giunea savanna     EIBSI  HIG10

[96 rows x 5 columns]

In [107]:
tmp = metadata.copy()
tmp.index = tmp["Sample ID"]
tdf = tmp.loc[metadata.tsids][["Vegetation zone", "longitude", "Location"]]
#pd.concat([metadata, tdf], axis=1)
tdf.index = metadata.index
tdf["Sample ID"] = metadata.tsids
tdf
tdf.to_csv("Hoplo_metadata_transpose_V2.csv")

In [4]:
metadata = pd.read_csv("Hoplo_metadata_transpose_V2.csv")
metadata

      Seq ID  Vegetation zone longitude  Location Sample ID
0   HOOC0001  Mangrove Forest      BAIK   Badagry     HBG 1
1   HOOC0002  Mangrove Forest      BAIK   Ikorodu      HIK3
2   HOOC0003  Mangrove Forest     EIBSI       Epe      HEP6
3   HOOC0004       Rainforest     EIBSI    Ibadan     HIB 9
4   HOOC0005       Rainforest      ADIF   Ifetedo    H IF 1
..       ...              ...       ...       ...       ...
91  HOOC0092       Rainforest      BAIK  Abeokuta     HAB10
92  HOOC0093  Derived savanna     EIBSI       Iwo      HIW2
93  HOOC0094  Derived savanna      ADIF       Ado    H AD 4
94  HOOC0095  Derived savanna     EIBSI      Soku      HSK8
95  HOOC0096   Giunea savanna     EIBSI    Igbeti    HIG10

[96 rows x 5 columns]

In [14]:
latlongs = pd.read_csv("Raw_latlongs.txt", sep="\t", index_col="Label")
#latlongs.loc[metadata["Sample ID"]]
metadata["Sample ID"].values
latlongs.index

Index(['HBG 1', 'HBG 2', 'HBG3', 'HBG4', 'HBG5', 'HBG6', 'HBG7', 'HBG8',
       'HBG9', 'HBG10', 'HIK1', 'HIK2', 'HIK3', 'HlK5', 'HlK6', 'HlK7', 'HlK8',
       'HlK9', 'HlK10', 'HEP1', 'HEP2', 'HEP3', 'HEP4', 'HEP5', 'HEP6', 'HEP7',
       'HEP8', 'HEP9', 'HEP10', 'HIB 1', 'HIB 2', 'HIB 3', 'HIB 4', 'HIB 5',
       'HIB 6', 'HIB 7', 'HIB 9', 'HIB 10', 'HAB1', 'HAB2', 'HAB3', 'HAB4',
       'HAB5', 'HAB6', 'HAB7', 'HAB8', 'HAB9', 'HAB10', 'H IF 1', 'H IF 2',
       'H IF 3', 'H IF 4', 'H IF 5', 'H IF 6', 'H IF 7', 'H IF 8', 'H IF 9',
       'H IF 10', 'HIW1', 'HIW2', 'HIW3', 'HIW4', 'HIW5', 'HIW6', 'HIW7',
       'HIW8', 'HIW9', 'HIW10 ', 'H AD 1', 'H AD 2', 'H AD 3', 'H AD 4',
       'H AD 5', 'H AD 6', 'H AD 7', 'H AD 8', 'HSK1', 'HSK2', 'HSK3', 'HSK4',
       'HSK5', 'HSK6', 'HSK7', 'HSK8', 'HSK9', 'HSK10', 'HIG1', 'HIG2', 'HIG3',
       'HIG4 ', 'HIG5 ', 'HIG6 ', 'HIG7', 'HIG8', 'HIG9 ', 'HIG10 '],
      dtype='object', name='Label')